---
# tasks file for route53-ansible-role

- apt: name={{ item }} state=latest
  with_items:
  - python3
  - python3-setuptools

- shell: easy_install3 pip

- pip: executable=/usr/local/bin/pip3 name={{ item }} state=latest
  with_items: python3_pip_packages
